let csrf='';
const byId=id=>document.getElementById(id);
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(response.status===401?'Inicia sesión para continuar':data.error||'Error de conexión');return data;}
function showError(error){byId('message').textContent=error.message;}
function renderPositions(data){byId('holdings').hidden=false;byId('position-list').replaceChildren();for(const p of data.positions||[]){const item=document.createElement('li');item.textContent=`${p.symbol} · ${p.quantity} unidades · entrada ${p.entry_price} · stop ${p.stop_price} · objetivo ${p.take_profit}`;byId('position-list').append(item);}const at=Date.parse(data.last_cycle_at);byId('engine-time').textContent=Number.isFinite(at)?`Último ciclo del motor: ${new Date(at).toLocaleString()}${Date.now()-at>1800000?' · SIN CICLOS RECIENTES':''}`:'Sin ciclos del motor registrados';}
async function refresh(){try{const state=await api('/v1/status');csrf=state.csrf;byId('login').hidden=true;byId('dashboard').hidden=false;byId('message').textContent='';byId('connection').textContent=state.stale?'SIN CONEXIÓN RECIENTE · El estado puede estar desactualizado':'Windows conectado · última recepción '+new Date(state.received_at*1000).toLocaleString();byId('metrics').replaceChildren();const data=state.snapshot||{};renderPositions(data);for(const [label,value] of [['Equity',data.equity],['Efectivo',data.cash],['Exposición',data.exposure],['Entradas',data.killed?'Pausadas':'Habilitadas']]){const card=document.createElement('div');card.className='card';card.textContent=label;const strong=document.createElement('strong');strong.textContent=value===undefined?'—':typeof value==='number'?value.toFixed(2)+' USDT':value;card.append(strong);byId('metrics').append(card);}byId('commands').replaceChildren();for(const command of state.commands){const item=document.createElement('li');item.textContent=`#${command.id} · ${command.action} · ${command.status}`;byId('commands').append(item);}byId('resume').disabled=state.stale;}catch(error){showError(error);}}
byId('login').addEventListener('submit',async event=>{event.preventDefault();try{const data=await api('/v1/login',{password:byId('password').value});byId('password').value='';csrf=data.csrf;await refresh();}catch(error){showError(error);}});
for(const action of ['kill','resume'])byId(action).onclick=async()=>{if(action==='resume'&&!confirm('¿Reanudar las entradas PAPER con los límites locales actuales?'))return;try{await api('/v1/commands',{action,request_id:crypto.randomUUID()});await refresh();}catch(error){showError(error);}};
byId('logout').onclick=async()=>{try{await api('/v1/logout',{});location.reload();}catch(error){showError(error);}};
setInterval(()=>{if(!document.hidden&&!byId('dashboard').hidden)refresh();},30000);refresh();
